### Get all bewerber
GET http://localhost:3000/api/bewerber

### Get specific bewerber
GET http://localhost:3000/api/bewerber/1

### Add bewerber
POST http://localhost:3000/api/bewerber
Content-Type: application/json

{
  "praktikumId": 1,
  "schuelerId": 1,
  "bewerbungFileName": "test.pdf"
}

### Update bewerber
PUT http://localhost:3000/api/bewerber/1
Content-Type: application/json

{
  "praktikumId": 1,
  "schuelerId": 2,
  "bewerbungFileName": "test.pdf"

}

### Delete bewerber
DELETE http://localhost:3000/api/bewerber/5