### Get specific firma
GET http://localhost:3000/api/firmen/1

### Add firma
POST http://localhost:3000/api/firmen
Content-Type: application/json

{
    "name": "Linux",
    "email" : "ds@email.com",
    "passwort" : "123456789",
    "beschreibung" : "Wir sind eine Firma",
    "adresse" : "Kreimlstrasse 5",
    "telefon" : "123456789"
  }

### Update firma
PUT http://localhost:3000/api/firmen/2
Content-Type: application/json

{
  "name": "Apple",
  "email" : "a@a",
  "passwort" : "1",
  "beschreibung" : "Wir sind ein Unternehmen",
  "adresse" : "Bahnstraße 100",
  "telefon" : "123456789"
}


### Delete firma
DELETE http://localhost:3000/api/firmen/3
