### Get all praktika of a firme
GET http://localhost:3000/api/praktika/firma/1

### Get a specific praktikum
GET http://localhost:3000/api/praktika/2

### Add praktikum
POST http://localhost:3000/api/praktika
Content-Type: application/json

{
  "titel": "Prakikum in der Informatik",
  "beschreibung": "1 Montat praktikum in der Informatik \n Aufgaben: \n Entwickeln von Software \n Testen von Software \n Dokumentation von Software",
  "anforderungen": "Currently pursuing a degree in Computer Science or related field  \n  Strong programming skills in languages such as Java, Python, or C++  \n Good problem-solving abilities   \nExcellent communication and teamwork skills",
  "firma": 1,
  "dauertage": 30,
  "gehalt": 1000
}

### Add praktikum
PUT http://localhost:3000/api/praktika/5
Content-Type: application/json

{
"titel": "KYSSSSS",
"beschreibung": "Beschreibung 1",
"anforderungen": "Baba programmierer",
"firma": 1,
"dauertage": 30,
"gehalt": 1000
}

### Delete schueler
DELETE http://localhost:3000/api/praktika/4