### Get all schueler
GET http://localhost:3000/api/schueler/

### Get specific schueler
GET http://localhost:3000/api/schueler/1

### Add/Update schueler
PUT http://localhost:3000/api/schueler/2
Content-Type: application/json

{
  "name": "Max Mustermann",
  "email": "max@mustermann",
  "address": "Musterstraße 1",
  "telefon": "0123456789"
}

### Delete schueler
DELETE http://localhost:3000/api/schueler/1