### Get all schueler
GET http://localhost:3000/api/schueler/

### Get specific schueler
GET http://localhost:3000/api/schueler/1

### Add/Update schueler
PUT http://localhost:3000/api/schueler/2
Content-Type: application/json

{
  "name": "Max Mustermann",
  "email": "max@mustermann",
  "password": "123456",
  "address": "Musterstraße 1",
  "telefon": "0123456789"
}

### Add schueler
POST http://localhost:3000/api/schueler
Content-Type: application/json

{
  "name": "Arnold Schwarzenegger",
  "email": "arnold@htl",
  "passwort": "123456",
  "adresse": "Musterstraße",
  "telefon": "0123456789"
}


### Delete schueler
DELETE http://localhost:3000/api/schueler/1

### Login
GET http://localhost:3000/api/schueler/login/try?email=f.stro@htl&passwort=123
