= Internship
:toc: left
:sectnums:
:toclevels: 1
:table-caption:

----
contact: b.bajtik@students.htl-leonding.ac.at
         o.daxinger@students.htl-leonding.ac.at
         l.nestler@students.htl-leonding.ac.at
         f.stroschneider@students.htl-leonding.ac.at
----

== Beschreibung

Die Praktikumsverwaltung ist eine Webanwendung, die Unternehmen und Schüler/innen zusammenbringt. Unternehmen können hier ihre Praktikumsplätze ausschreiben und Schüler/innen haben die Möglichkeit, sich darauf zu bewerben.

== Klassendiagramm

.Klassendiagramm
[%collapsible]
====
[plantuml,structure,png]
----
include::asciidocs/plantuml/Klassendiagramm.puml[]
----
====

== Anforderungen

=== Unternehmen registrieren

Unternehmen müssen sich auf der Plattform registrieren und ihr Unternehmen und ihre Praktikumsplätze hinzufügen können.

=== Schüler registrieren

Schüler/innen müssen sich ebenfalls auf der Plattform registrieren und ein Profil erstellen können.

=== Schüler bewerben

Schüler/innen müssen in der Lage sein, sich auf Praktikumsplätze zu bewerben, indem sie eine Bewerbung und einen Lebenslauf einreichen.

=== Unternehmen Bewerbungen sehen

Unternehmen müssen die Möglichkeit haben, die eingereichten Bewerbungen zu durchsuchen und mit den Schüler/innen in Kontakt zu treten, die ihnen am meisten zusagen.

== Funktionen

=== Registrierung und Anmeldung:

Die Plattform muss eine Registrierung und Anmeldung für Unternehmen und Schüler/innen bereitstellen.

=== Profilverwaltung:

Unternehmen und Schüler/innen müssen ihre Profile verwalten und bearbeiten können.

=== Praktikumsplätze ausschreiben:

Unternehmen müssen in der Lage sein, ihre Praktikumsplätze auf der Plattform zu veröffentlichen.

=== Bewerbungen einreichen:

Schüler/innen müssen in der Lage sein, sich auf Praktikumsplätze zu bewerben, indem sie eine Bewerbung und einen Lebenslauf einreichen.

=== Bewerbungsverwaltung:

Unternehmen müssen die eingereichten Bewerbungen durchsuchen und mit den Schüler/innen in Kontakt treten können.

=== Benachrichtigungen:

Die Plattform muss Benachrichtigungen über neue Praktikumsplätze und Bewerbungen bereitstellen.

=== Suchfunktion:

Die Plattform muss eine Suchfunktion bereitstellen, mit der Schüler/innen nach Praktikumsplätzen suchen können.

*.js
